### ISSUE TITLE
Sms notifications broke, what version works?

### ISSUE THREAD

**Issue by plaurent** [alexr4535/siglo#53] opened 2021-06-01 00:16 UTC
In a previous version experimental pairing allowed sms notifications from chatty under Mobian to work. What version was that?  And will Sms notifications be coming back soon?

**Comment by alexr4535** [comment] 2021-06-01 14:49
this broke with the new UI refresh for v0.8.0, so if you want SMS notifications you need to checkout the tag before that for now. (v0.7.4) Closing this as its a duplicate of https://github.com/alexr4535/siglo/issues/49

**Closed by alexr4535** 2021-06-01 14:49 UTC

**Comment by plaurent** [comment] 2021-06-01 14:51
Thank you!
